"""Config flow for the Linux Focus Mode integration.

The Linux app registers itself with HA via the mobile_app protocol and
receives a webhook_id. The user copies that webhook_id here so the
integration knows which webhook to listen on for state push events.

No host/IP/port is needed — all communication is initiated by the app.
"""

from __future__ import annotations

import logging
from typing import Any

import voluptuous as vol

from homeassistant import config_entries
from homeassistant.components.webhook import async_generate_url
from homeassistant.data_entry_flow import FlowResult

from .const import CONF_WEBHOOK_ID, DOMAIN

_LOGGER = logging.getLogger(__name__)

STEP_USER_DATA_SCHEMA = vol.Schema(
    {
        vol.Required(CONF_WEBHOOK_ID): str,
    }
)


class LinuxFocusModeConfigFlow(config_entries.ConfigFlow, domain=DOMAIN):
    """Config flow: user provides the webhook_id generated by the Linux app."""

    VERSION = 1

    async def async_step_user(
        self, user_input: dict[str, Any] | None = None
    ) -> FlowResult:
        """Single step — paste the webhook_id from the Linux app."""
        errors: dict[str, str] = {}

        if user_input is not None:
            webhook_id = user_input[CONF_WEBHOOK_ID].strip()
            if not webhook_id:
                errors[CONF_WEBHOOK_ID] = "invalid_webhook_id"
            else:
                webhook_url = async_generate_url(self.hass, webhook_id)
                return self.async_create_entry(
                    title="Linux Focus Mode",
                    data={
                        CONF_WEBHOOK_ID: webhook_id,
                        "webhook_url": webhook_url,
                    },
                )

        return self.async_show_form(
            step_id="user",
            data_schema=STEP_USER_DATA_SCHEMA,
            description_placeholders={
                "app_instruction": (
                    "Start the Linux app → Settings → HA Integration → "
                    "click Register. Copy the Webhook ID shown by the app."
                )
            },
            errors=errors,
        )
